# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9d00cd5c77142fe472ca382985922b8bc9cef714f23f26ddc19dfd9c37bc5dc889b20817695e9e01c6beedc83dfe2809d0d03e92a73032ea760dca2551c0ea5

test:
  secret_key_base: a09fa3d2a9ca8609a2a53c2cf2ba0bb113dcb49da36dad56a1c7a45d7ac93fd23f55af712a280ac254ec1e8a9f5c990a25ebfbd4865766fe3cba989716a4890d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
